### ISSUE TITLE
No search of browse to locate content

### ISSUE THREAD

**Issue by uskudarli** [SWE-574-Spring-2018/LinkyWay#102]
No way to get around or find nodes, relatioships, within the network.

There should be a way to search for nodes (with given relations). Or at least nodes and relation names.

Also search within the bodies of annotations.

**Comment by uskudarli** [comment]
This is hopeless. I created a new node and want to connect it. I need to access the new node. There is no way.

**Comment by salih-demir** [comment]
Node search implemented. It will be available after second release.
